### Create a new todo item
POST https://localhost:7219/todoitems
Content-Type: application/json

{
  "name": "New Task",
  "isComplete": false
}

###

### Get all to-do items
GET https://localhost:7219/todoitems
Accept: application/json

###

### Get all completed to-do items
GET https://localhost:7219/todoitems/complete
Accept: application/json

###

### Get a to-do item by ID
GET https://localhost:7219/todoitems/1
Accept: application/json

###

### Update a todo item (ID = 1)
PUT https://localhost:7219/todoitems/1
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete": false
}

###

### Delete a todo item (ID = 1)
DELETE https://localhost:7219/todoitems/1

###